# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Q_ASSERT
tagline:             'ExAMYEs'
description:         'nothing matters'
url:                 http://qassert.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ExAMYEs
  url:               http://qassert.com
  email:             461507150@qq.com

# Custom vars
version:             1.0.0
